### ISSUE TITLE
[Bug] Save button does not enable when model properties are changed

### ISSUE THREAD

**Issue by petersonbrock** [associatedemployers/granite#205]
account/employee/edit

**Comment by James1x0** [comment]
@petersonbrock Specifically relationships. This could possibly be fixed by adding an intermediary action that marks the model as dirty if the select box is changed. Another possible solution might be eaching over the relationships and seeing dirty status there, reducing into a CP as described here: https://paulferrett.com/2014/ember-model-isdirty-when-belongsto-changes/
